server:
  port: 8096
  
spring:
  application:
    name: gateway
    
zuul:
  routes:  
    uaa:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: oauth-server
    resource:
      path: /resource/**
      sensitiveHeaders: 
      serviceId: resource-server
    host:
      socket-timeout-millis: 3000
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
      
security:
  oauth2:    
    client:
      accessTokenUri: http://localhost:9000/uaa/oauth/token
      userAuthorizationUri: http://localhost:9000/uaa/oauth/authorize
      clientId: 
      clientSecret: alo   
    resource:
      userInfoUri: http://localhost:9000/uaa/user
      preferTokenInfo: false  
  sessions: ALWAYS
